### ISSUE TITLE
Erreur lib python

### ISSUE THREAD

**Issue by flemzord** [ftx/monitoring-opentsdb-iot-ovh#3]
Bonjour, 

Je rencontre de nombreuse erreur sur la lib python qui permet d'envoyer les données. 
##### 

-> # sh monitoring.sh
[{u'timestamp': 1452696749, u'metric': 'TEST.PP-CLOUD-WEB-01.TEST.nombrePublication', u'value': 650.0, u'tags': {'iot': 'metrics'}}]
Send successful
Response code from server: 204
[{u'timestamp': 1452696749, u'metric': 'TEST.PP-CLOUD-WEB-01.TEST.nombrePublicationtotal', u'value': 775.0, u'tags': {'iot': 'metrics'}}]
^CTraceback (most recent call last):
  File "/opt/monitoring-opentsdb-iot-ovh/bin/iot.py", line 54, in <module>
    auth=(token_id, token_key))
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 203, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, *_extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(_args)
KeyboardInterrupt
##### 

Maxence

**Comment by ftx** [comment]
Hello,

Tu peux me montrer le fichier ?
J'imagine que tu a réadapté à ton usage.

Florian

**Comment by flemzord** [comment]
Le fichier python n'a eu aucune modification. Or l'ajout des identifiants 

Voici les appels : python $PATH_M/bin/iot.py "$CLIENT.$NODE.publishpaper.nombrePublicationtotal" iot metrics "$NBR_PUBLICATION_TOTAL"

**Comment by ftx** [comment]
Je ne saurai te dire, étant un soucis interne à ton OS.
Tente de reinstaller la lib + MaJ au besoin.
